CF_Crawler/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
]

main/urls.py
from django.urls import path
from . import views as v
from users import views as v1
from django.conf.urls import url


app_name='main'

urlpatterns = [
    path('', v.home, name='home'),
    path('cfhandle/', v.cfhandle, name="cfhandle"),
    path('cfhandle/<str:handle>', v.who, name='who'),
    path('timetable/', v.time_table, name="time_table"),
    path('timetable/codeforces', v.code_forces, name="code_forces"),
    path('timetable/codechef', v.code_chef, name="code_chef"),
    path('contest/<str:handle>', v.contest, name='contest-statistics'),
    path('contact/', v.contact, name='contact'),
    path('iitg/', v.iitg, name='iitg'),
    path('allchat/', v.allchat, name='allchat'),
    path('chatroom/<str:userid1>/<str:userid2>/', v.chatroom, name='chatroom'),
]

main/models.py
from django.db import models

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.
class languages(models.Model):
    name = models.CharField(max_length = 200)
    val = models.IntegerField()

    def __str__(self):
        return self.name

class verdicts(models.Model):
    name = models.CharField(max_length = 200)
    val = models.IntegerField()

    def __str__(self):
        return self.name

class Contact(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE)
    friends = models.ManyToManyField('self', blank=True)

    def __str__(self):
        return self.user.username

class levels(models.Model):
    name = models.CharField(max_length = 200)
    val = models.IntegerField()

    def __str__(self):
        return self.name


class Chatroom(models.Model):
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user1')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user2')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)


    class Meta:
        unique_together = (("user1", "user2"),)

class Chatmessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    chatroom = models.ForeignKey(Chatroom,  on_delete=models.CASCADE)

    def __str__(self):
        return self.message

templates/allchat.html
{% extends "base.html" %}

{% block content %}


{% for user_ in alluser %}

{% if user.id is not user_.id %}
    <a class="navbar-link" href="{% url 'main:chatroom' user.id user_.id %} ">{{user_}} -- {{user_.id}} </a><br>
{% endif %}


{% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'js/main.js' %}"></script>
    <script type="text/javascript" src="{% static 'fusioncharts/fusioncharts.js' %}"> </script>
    <script type="text/javascript" src="{% static 'fusioncharts/fusioncharts.charts.js' %}"></script>
    <script type="text/javascript" src="{% static 'fusioncharts/themes/fusioncharts.theme.fusion.js' %}"></script>
</head>

{% load socialaccount %}
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <ul class="nav navbar-nav">
            {# Django Home Link / Admin Link / Register Link#}
  
            <li><a class="navbar-brand" href="{% url 'main:home' %}">CF Crawler</a></li>
            <li><a class="navbar-link" href="{% url 'main:time_table' %}">Coder Calendar</a></li>
            <li><a class="navbar-link" href="{% url 'main:iitg' %} ">IIT-G</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            {% if not user.is_authenticated %}
            {% else %}
            <li><a class="navbar-link" href="{% url 'main:cfhandle' %} ">Search Handle</a></li>
            <li><a class="navbar-link" href="{% url 'main:contact' %}">Contact Us</a></li>
            <li><a class="navbar-link" href="{% url 'main:allchat' %}">Chat</a></li>
            {% endif %}


        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if not user.is_authenticated %}
              <li><a class="navbar-link" href="{% url 'account_signup' %}">Register</a></li>
              <li><a class="navbar-link" href="{% url 'account_login' %}">Login</a></li>
            {% else %}
            <li><a class="navbar-link" href="{% url 'account_logout' %}">Logout</a></li>
            {% endif %}
        </ul>


    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

templates/cchef.html
{% extends 'base.html' %}

{% block title %}
Code Chef TT
{% endblock %}

{% block content %}
<h2>Contest Details of Current running Contests:</h2>

<div class="contest-view">
    
        <ul>
            {% for info in dic1 %}
                <br>
                <li><h4>Name:<a href="https://www.codechef.com/contests"> {{info.1}}</a></h4></li>
                <h4>Code: {{info.0}}</h4>
                <h4>Start Date and Time: {{info.2}}</h4>
                <h4>End Date and Time: {{info.3}}</h4>
                <br>
            {% endfor %}
            
        </ul>
    
</div>

<h2>Contest Details of Upcoming Contests:</h2>

<div class="contest-view">
    
        <ul>
            {% for info in dic2 %}
                <br>
                <li><h4>Name:<a href="https://www.codechef.com/contests"> {{info.1}}</a></h4></li>
                <h4>Code: {{info.0}}</h4>
                <h4>Start Date and Time: {{info.2}}</h4>
                <h4>End Date and Time: {{info.3}}</h4>
                <br>
            {% endfor %}
            
        </ul>
    
</div>
{% endblock %}

templates/cf.html
{% extends 'base.html' %}

{% block title %}
Code Forces TT
{% endblock %}

{% block content %}
<h2>Contest Details of Upcoming Contests:</h2>

<div class="contest-view">
    
        <ul>
            {% for info in dic %}
                <br>
                <li><h4>Name:<a href="https://codeforces.com/contests"> {{info.0}}</a></h4></li>
                <h4>Creator: {{info.1}}</h4>
                <h4>Start Date and Time: {{info.2}}</h4>
                <h4>Duration: {{info.3}}</h4>
                <h4>Remaining Time/Days: {{info.4}}</h4>
                <br>
            {% endfor %}
            
        </ul>
    
</div>
{% endblock %}

templates/chat.html
{% extends "base.html" %}

{% block content %}

<ul id='chat-items'>
    <input type="hidden" id="myusername" value="{{user.username}}">
{% for message in messages %}

<li>{{ message.message }} via {{message.user.username}}</li>

{% endfor %}
</ul>


<form method="post" action="#" id="form">
    {% csrf_token %}
  <textarea name="answer" rows="1" cols="10" style=" background-color: #CCE5FF " id="id_message"></textarea>
  <br>
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">ans</button>
</form>



<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js"></script>

<script>
console.log(window.location)
var loc = window.location
var myDate = new Date();


var formdata = $('#form')
var msginput = $('#id_message')
var chatholder = $('#chat-items')

const  socket = new ReconnectingWebSocket('ws://' + loc.host +  loc.pathname)
console.log(socket)



socket.onopen = function(e){
                    formdata.submit(function(event)
                    {
                        console.log("prevent default")
                        event.preventDefault()

                        var finaldata = {
                            'message': msginput.val()
                        }
<!--                    chatholder.append('<li>' + msginput.val() +  " via " + me  + '</li>')-->

                        socket.send(JSON.stringify(finaldata))   <!-- go to websocket_receive -->

                        formdata[0].reset()  <!-- clear the form method 1 -->
<!--                    msginput.val('')    &lt;!&ndash; clear the form method 2 &ndash;&gt;-->
                    })

                    console.log("falak js open", e)}



socket.onmessage = function(e){
                    var data = JSON.parse(e.data)

                    if (data.message)
                        chatholder.append('<li>'  + data.message + " via " +  data.username  + '</li>')

                    console.log("falak js message", e)}


socket.onerror = function(e){
                    console.log("falak js error", e)}

socket.onclose = function(e){
                    console.log("falak js close", e)}


</script>
{% endblock %}

templates/contact.html
{% load static %}
<html lang="en">
<head>
	<title>Contact us</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>


	<div class="container-contact100">
		<div class="wrap-contact100">
			<form class="contact100-form validate-form">
				<span class="contact100-form-title">
					Send Us A Message
				</span>


				<div class="wrap-input100 validate-input" data-validate="Name is required">
					<label class="label-input100" for="name">Full name</label>
					<input id="name" class="input100" type="text" name="name" placeholder="Enter your name...">
					<span class="focus-input100"></span>
				</div>


				<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
					<label class="label-input100" for="email">Email Address</label>
					<input id="email" class="input100" type="text" name="email" placeholder="Enter your email...">
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100">
					<div class="label-input100">What do you need?</div>
					<div>
						<select class="js-select2" name="service">
							<option>Please chooses</option>
							<option>UI/UX Design</option>
							<option>eCommerce Bussiness</option>
							<option>Online Services</option>
						</select>
						<div class="dropDownSelect2"></div>
					</div>
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate = "Message is required">
					<label class="label-input100" for="message">Message</label>
					<textarea id="message" class="input100" name="message" placeholder="Type your message here..."></textarea>
					<span class="focus-input100"></span>
				</div>

				<div class="container-contact100-form-btn">
					<button class="contact100-form-btn">
						Send
					</button>
				</div>

				<div class="contact100-form-social flex-c-m">
					<a href="#" class="contact100-form-social-item flex-c-m bg1 m-r-5">
						<i class="fa fa-facebook-f" aria-hidden="true"></i>
					</a>

					<a href="#" class="contact100-form-social-item flex-c-m bg2 m-r-5">
						<i class="fa fa-twitter" aria-hidden="true"></i>
					</a>

					<a href="#" class="contact100-form-social-item flex-c-m bg3">
						<i class="fa fa-youtube-play" aria-hidden="true"></i>
					</a>
				</div>
			</form>

			<div class="contact100-more flex-col-c-m" style="background-image: url({% static 'images/bg-01.jpg' %});">
			</div>
		</div>
	</div>





<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
	<script>
		$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});
		})
		$(".js-select2").each(function(){
			$(this).on('select2:open', function (e){
				$(this).parent().next().addClass('eff-focus-selection');
			});
		});
		$(".js-select2").each(function(){
			$(this).on('select2:close', function (e){
				$(this).parent().next().removeClass('eff-focus-selection');
			});
		});

	</script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-23581568-13');
	</script>
</body>
</html>

templates/contest_stats.html
{% extends "base.html" %}

{% block title %}
User-Profile
{% endblock %}

{% block content %}

    <div id="languages_chart">
        {{output_languages | safe}}
    </div>

    <div id="verdicts_chart">
        {{output_verdicts | safe}}
    </div>

    <div id="levels_chart">
        {{output_levels | safe}}
    </div>

    <div class="w-25 p-3">
        <table class="table table-striped">

            <thead>
                <tr class="bg-primary">
                    <th scope="col">Contest Stats </th>
                    <th scope="col">{{Handle}}</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <th scope="row">
                        Best Rank
                    </th>

                    <td> {{Best_Rank}} </td>
                </tr>

                <tr>
                    <th scope="row">
                        Worst Rank
                    </th>

                    <td> {{Worst_Rank}} </td>
                </tr>

                <tr>
                    <th scope="row">
                        Max Up
                    </th>

                    <td> {{Max_Up}} </td>
                </tr>

                <tr>
                    <th scope="row">
                        Max Down
                    </th>

                    <td> {{Max_Down}} </td>
                </tr>
            </tbody>

        </table>
    </div>


{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %} CF Crawler {% endblock %}
{% load socialaccount %}

{% block content %}


<div class="container">
    <div class="jumbotron" style="background-color: rgb(233, 224, 211);">
      <h1>Welcome to the CF Crawler!</h1>
      {% if user.is_authenticated %}
          <h2>Hello <strong>{{ user.username }}</strong></h2>
<!--            <h2>Hello <strong>{{ user.id }}</strong></h2>-->
      {% else %}
          <h2>Register or Login if you want to know about other coders</h2>
      {% endif %}
    </div>
  </div>
    
{% endblock %}

templates/iitg.html
{% extends "base.html" %}
{% block title %}
Handle Info
{% endblock %}
{% block content %}

<table>
<tbody>
<tr>
    <th style="width:2em;" class="top left">&nbsp;</th>
    <th style="text-align:left;" class="top">Who</th>
    <th style="text-align:left;" class="top">Color&nbsp&nbsp</th>
    <th style="width:2em;" class="top"><span title="Number of participations">#</span></th>
    <th style="width:2em;" class="top right">=</th>
</tr>

{% for items in dic %}
<tr>
    <td class="dark left">
            {{items.0}}
    </td>
    <td style="text-align:left;padding-left:1em;" class="dark">
        <a href="{% url 'main:who' items.1 %}">{{items.1}}</a>    </td>
    <td class="dark">
        {{items.2}}
    </td>
    <td class="dark">
        {{items.3}}
    </td>
    <td class="dark right">
        {{items.4}}
    </td>
</tr>

{% endfor %}
</tbody>
</table>







{% endblock %}

templates/options.html
{% extends "base.html" %}
{% block title %}
Handle Info
{% endblock %}
{% block content %}
<div class="col-lg-6 col-md-7 col-sm-8">
    <div class="banner-content">
        <h2><strong>{{ handle }}'s</strong> Information</h2><br>
        <ul>
<!--            <li><a href="/submission/{{ handle }}">Submission Stats</a></li><br>-->
            <li><a href="/contest/{{ handle }}">Contest Stats</a></li>

    </div>
</div>
{% endblock %}

templates/searchhandle.html
{% extends 'base.html' %}

{% block title %}
Search Handle
{% endblock %}
{{error}}dvvvvvvvvv
{% load crispy_forms_tags %}

{% block content %}
<h3>Enter CodeForces Handle &nbsp&nbsp&nbsp&nbsp{{error}}</h3>
<div class="jumbotron " style="background-color: rgb(233, 224, 211);">
<!--    falak add-->
    <form method="POST" class="form-group" action="{% url 'main:cfhandle' %}">
        {% csrf_token %}
        {{form | crispy}}
        <button type="submit" class="btn btn-success">Search</button>
    </form>

</div>
{% endblock %}

templates/sub_stats.html
{% extends "base.html" %}
{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>
      <div class="container" style="position: relative; height:700px; width:700px">
            <canvas id="myChart"></canvas>
      </div>
      <div class="container" id="chart2"style="position: relative;" ></div>
<script>
    let myChart = document.getElementById('myChart').getContext('2d');
    // Global Options
    Chart.defaults.global.defaultFontFamily = 'Arial';
    Chart.defaults.global.defaultFontSize = 18;
    Chart.defaults.global.defaultFontColor = '#777';

    let SubmissionsChart = new Chart(myChart, {
      type:'pie', // bar, horizontalBar, pie, line, doughnut, radar, polarArea
      data:{
        labels:['Accepted', 'Hacked', 'Wrong Answer', 'Runtime Error', 'Time Exceeded', 'Compilation Error'],
        datasets:[{
          label:'Submissions',
          data:[
                '{{ accepted }}',
                '{{ hacked }}',
                '{{ wrong_answer }}',
                '{{ runtime_error }}',
                '{{ time_exceed }}',
                '{{ compilation_error }}'
          ],
          //backgroundColor:'green',
          backgroundColor:[
            'rgba(20,180,0,0.9)',
            'rgb(60,20,125)',
            'rgba(100,0,32,0.8)',
            'rgba(140,70,70,0.5)',
            'rgba(180, 115, 255, 0.6)',
            'rgba(220, 0, 64, 0.6)',
            'rgba(255, 100, 132, 0.6)'
          ],
          borderWidth:1,
          borderColor:'#777',
          hoverBorderWidth:3,
          hoverBorderColor:'#000'
        }]
      },
      options:{
        title:{
          display:true,
          text:'Submissions Till Date',
          fontSize:35,
            fontColor: '#000'
        },
        legend:{
          display:true,
          position:'right',
          labels:{
            fontColor:'#000'
          }
        },
        tooltips:{
          enabled:true
        },
        layout:{
          padding:{
            left:50,
            right:0,
            bottom:0,
            top:0
          }
        }
      }
    });
  </script>
{% endblock %}

templates/time_table.html
{% extends 'base.html' %}

{% block title %}
Time Table
{% endblock %}

{% block content %}
<h2>Click and get Contest Time Table of respective coding site:</h2>
<div class="sites">
    
    
        <ul>
            <br>
            <li><a href="{% url 'main:code_forces' %}"><h4>Code Forces</h4></a></li>
            <li><a href="{% url 'main:code_chef' %}"><h4>Code Chef</h4></a></li> 
                
        </ul>
        
    
</div>
{% endblock %}